name: PR

on: [pull_request]

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: yarn

#      - name: Check linting
#        run: yarn lint
#
#      - name: Run unit tests
#        run: yarn test:coverage
#
#      - name: Upload codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
