name: Release

on:
  push:
  - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Install deps
      run: |
        yarn
