name: Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v2.1.1
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
