name: Release

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Install deps
      run: |
        yarn

    - name: Create Android build
      uses: MrRamych/gradle-actions/openjdk-12@2.1
      with:
        working-directory: android
        args: assembleProd
