name: Release

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8

    - name: Install deps
      run: |
        yarn

    - name: Create Android build
      run: |
        cd ./android
        ./gradlew assembleProd
